apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: check-api                 # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: check-api
---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: check-api          # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: check-api       
  template:                      
    metadata:
      labels:                    
        app: check-api
    spec:                        
      containers:
      - name: check-api
        image: 111098/check:latest2
        imagePullPolicy: IfNotPresent
        env:
        - name: db
          value: db

        ports:
          - containerPort: 8000

